/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class ClientSchema
    {
        public const string Table = "identity.client";

        public static class Columns
        {    
            public static string Id = "id";
            public static string Name = "name";
            public static string Secret = "secret";
            public static string Description = "description";
            public static string ApplicationType = "application_type";
            public static string Active = "active";
            public static string AccessTokenLifeTime = "access_token_life_time";
            public static string RefreshTokenLifeTime = "refresh_token_life_time";
            public static string AllowedOrigin = "allowed_origin";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string RefreshTokens = "refresh_tokens";
            public static string EmailTemplates = "email_templates";
        }
    }
}