/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class RoleSchema
    {
        public const string Table = "identity.role";

        public static class Columns
        {    
            public static string Id = "id";
            public static string Name = "name";
            public static string NormalizedName = "normalized_name";
            public static string ConcurrencyStamp = "concurrency_stamp";
            public static string Stackable = "stackable";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string Claims = "claims";
            public static string Users = "users";
        }
    }
}