/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class UserLoginSchema
    {
        public const string Table = "identity.user_login";

        public static class Columns
        {    
            public static string LoginProvider = "login_provider";
            public static string ProviderKey = "provider_key";
            public static string ProviderDisplayName = "provider_display_name";
            public static string Token = "token";
            public static string IsConfirmed = "is_confirmed";
            public static string UserId = "user_id";
            public static string User = "user";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
        }
    }
}