/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class UserSchema
    {
        public const string Table = "identity.user";

        public static class Columns
        {    
            public static string Id = "id";
            public static string UserName = "user_name";
            public static string NormalizedUserName = "normalized_user_name";
            public static string FirstName = "first_name";
            public static string LastName = "last_name";
            public static string Email = "email";
            public static string EmailConfirmed = "email_confirmed";
            public static string NormalizedEmail = "normalized_email";
            public static string PhoneNumber = "phone_number";
            public static string PhoneNumberConfirmed = "phone_number_confirmed";
            public static string PasswordHash = "password_hash";
            public static string TwoFactorEnabled = "two_factor_enabled";
            public static string LockoutEnabled = "lockout_enabled";
            public static string IsApproved = "is_approved";
            public static string AccessFailedCount = "access_failed_count";
            public static string ConcurrencyStamp = "concurrency_stamp";
            public static string SecurityStamp = "security_stamp";
            public static string LockoutEndDateUtc = "lockout_end_date_utc";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string Roles = "roles";
            public static string Claims = "claims";
            public static string Logins = "logins";
            public static string UserTokens = "user_tokens";
            public static string RefreshTokens = "refresh_tokens";
        }
    }
}