/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class UserClaimSchema
    {
        public const string Table = "identity.user_claim";

        public static class Columns
        {    
            public static string Id = "id";
            public static string UserId = "user_id";
            public static string User = "user";
            public static string ClaimType = "claim_type";
            public static string ClaimValue = "claim_value";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
        }
    }
}