/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class UserRefreshTokenSchema
    {
        public const string Table = "identity.user_refresh_token";

        public static class Columns
        {    
            public static string Value = "value";
            public static string UserId = "user_id";
            public static string User = "user";
            public static string ClientId = "client_id";
            public static string Client = "client";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string DateExpiresUtc = "date_expires_utc";
        }
    }
}