/** Generated by Liquid **/

namespace Store.DAL.Schema.Identity
{
    public static class UserRoleSchema
    {
        public const string Table = "identity.user_role";

        public static class Columns
        {    
            public static string UserId = "user_id";
            public static string User = "user";
            public static string RoleId = "role_id";
            public static string Role = "role";
            public static string DateCreatedUtc = "date_created_utc";
        }
    }
}