/** Generated by Liquid **/

using System;

namespace Store.Repository.Queries
{
    public static partial class SqlQueries
    {
        public static class Bookstore
        {
            public static partial class BookstoreDetailedReport
            {
                private static Lazy<string> _commandText = new Lazy<string>(() => GetSqlCommandText(@"SqlQueries\Bookstore\BookstoreDetailedReport.sql"));

                public static string CommandText
                {
                    get
                    {
                        return _commandText.Value;
                    }
                }

                public static class Parameters
                {
                    public static string Name = "@name";
                }          
           }
        }     
        public static class GlobalSearch
        {
            public static partial class SearchAllModules
            {
                private static Lazy<string> _commandText = new Lazy<string>(() => GetSqlCommandText(@"SqlQueries\GlobalSearch\SearchAllModules.sql"));

                public static string CommandText
                {
                    get
                    {
                        return _commandText.Value;
                    }
                }

                public static class Parameters
                {
                    public static string HasBookstoreRead = "@hasBookstoreRead";
                    public static string SearchPhrase = "@searchPhrase";
                    public static string HasBookRead = "@hasBookRead";
                }          
           }
        }     
    }
}