# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  azureSubscription: 'Visual Studio Enterprise Subscription – MPN(45a48931-c96a-4b38-80cf-be5fff673f85)'
  azureContainerRegistry: '{"loginServer":"storetestwesteu.azurecr.io", "id" : "/subscriptions/45a48931-c96a-4b38-80cf-be5fff673f85/resourceGroups/ContainerRegistry-West-EU/providers/Microsoft.ContainerRegistry/registries/storetestwesteu"}'
  dockerComposeFile: '**/docker-compose.yml'
  additionalDockerComposeFiles: 'docker-compose.test.yml'
  sshEndpoint: 'azureuser@137.116.221.238'
  dockerPath: '$(System.DefaultWorkingDirectory)/Store/Docker/'
  projectName: 'StoreApplication'
  vmProjectPath: '/home/azureuser/Projects/StoreApplicationCore/'

stages:
  - stage: Build_and_push_docker_containers
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      continueOnError: true
      steps:
      - task: DownloadSecureFile@1
        displayName: 'Download environment variables file - postgres server'
        inputs:
          secureFile: postgres-server_variables.env
          retryCount: 3
      - task: DownloadSecureFile@1
        displayName: 'Download environment variables file - pgadmin'
        inputs:
          secureFile: pgadmin_variables.env
          retryCount: 3
      - task: CopyFiles@2
        displayName: 'Copy environment variable files to: $(dockerPath)'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: '*.env'
          TargetFolder: $(dockerPath) 
      # - task: DockerCompose@0
      #   displayName: Build services
      #   inputs:
      #     containerregistrytype: 'Azure Container Registry'
      #     azureSubscription: $(azureSubscription)
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     dockerComposeFile: $(dockerComposeFile)
      #     additionalDockerComposeFiles: $(additionalDockerComposeFiles)
      #     projectName: $(projectName)
      #     action: 'Build services'
      # - task: DockerCompose@0
      #   displayName: Push services
      #   inputs:
      #     action: 'Push services'
      #     containerregistrytype: 'Azure Container Registry'
      #     azureSubscription: $(azureSubscription)
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     dockerComposeFile: $(dockerComposeFile)
      #     additionalDockerComposeFiles: $(additionalDockerComposeFiles)
      #     projectName: $(projectName)
      - task: PublishPipelineArtifact@1
        displayName: Publish pipeline artifact
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'docker-compose'
          publishLocation: 'pipeline'
  
  - stage: 'Deploy_to_test'
    jobs:
    - deployment: Test
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'StoreTestEnvironment'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CopyFilesOverSSH@0
              displayName: Copy store application repo over SSH
              inputs:
                sshEndpoint: $(sshEndpoint)
                sourceFolder: '$(Pipeline.Workspace)/docker-compose/s/'
                contents: '**'
                targetFolder: $(vmProjectPath)
                overwrite: true
            - task: SSH@0
              displayName: Run docker compose
              inputs:
                sshEndpoint: $(sshEndpoint)
                runOptions: 'inline'
                inline: |
                  cd $(vmProjectPath)/Store/Docker/
                  docker-compose down
                  docker-compose -f docker-compose.yml -f docker-compose.test.yml build
                  docker-compose -f docker-compose.yml -f docker-compose.test.yml up --force-recreate