/** Generated by Liquid **/

namespace Store.DAL.Schema
{
    public static class BookSchema
    {
        public const string Table = "book";

        public static class Columns
        {    
            public static string Id = "id";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string BookstoreId = "bookstore_id";
            public static string Bookstore = "bookstore";
            public static string Name = "name";
            public static string Author = "author";
        }
    }
}