/** Generated by Liquid **/

namespace Store.DAL.Schema
{
    public static class BookstoreSchema
    {
        public const string Table = "bookstore";

        public static class Columns
        {    
            public static string Id = "id";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string Name = "name";
            public static string Location = "location";
            public static string Books = "books";
        }
    }
}