/** Generated by Liquid **/

namespace Store.DAL.Schema
{
    public static class EmailTemplateSchema
    {
        public const string Table = "email_template";

        public static class Columns
        {    
            public static string Id = "id";
            public static string DateCreatedUtc = "date_created_utc";
            public static string DateUpdatedUtc = "date_updated_utc";
            public static string ClientId = "client_id";
            public static string Client = "client";
            public static string Type = "type";
            public static string Path = "path";
            public static string Name = "name";
        }
    }
}