version: '3.8'

services:
  web-api:
    build:
      context: ../
    restart: always
    ports:
      - 5000:443
    # Hosting ASP.NET Core images with Docker Compose over HTTPS:
    # https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-5.0
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres-server
      - redis-master

  postgres-server:
    image: postgres:13
    ports: 
      - 5432:5432
    restart: always

  redis-master:
    image: redis:6
    ports:
      - 6379:6379
  
  # Redis as a slave: https://redis.io/topics/config
  redis-slave-1:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6380:6379
      
  redis-slave-2:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6381:6379
      
  # Redis Sentinel: https://redis.io/topics/sentinel
  redis-sentinel:
    build: 
      context: ./redis-sentinel-cluster
    deploy:
      replicas: 3
    depends_on:
      - redis-master

# GENERAL:
## Docker Context: https://docs.docker.com/engine/context/working-with-contexts/
## Volume is mapped only when the Dockerfile has been built successfully.