version: '3.8'

services:
  web-api:
    build:
      args:
        PUBLISH_MODE: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      ASPNETCORE_URLS: https://+:443
      STOREAPP_KESTREL__CERTIFICATES__DEFAULT__PATH: /https/penic-solutions.com_self-signed.pfx

  postgres-server:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: Store
    env_file:
      - $(postgres-server_variables.env.secureFilePath)

  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
    env_file:
      - $(pgadmin_variables.env.secureFilePath)
    ports:
      - 5050:80