version: '3.8'

services:
  web-api:
    build:
      context: ../
      dockerfile: ./Store.WebAPI/Dockerfile
    restart: always
    ports:
      - 5000:80

  database-update:
    build:
      context: ../
      dockerfile: ./Docker/database-update/Dockerfile
    depends_on:
      - postgres-server
    volumes:
      - ../:/app

  postgres-server:
    image: postgres:13
    ports: 
      - 5060:5432
    restart: always
    depends_on:
      - web-api
    hostname: localhost

  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    ports:
      - 5050:80

  redis-master:
    image: redis:6
    ports:
      - 6379:6379
    depends_on:
      - web-api
  
  redis-slave-1:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6380:6379
      
  redis-slave-2:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6381:6379
      
  redis-sentinel:
    build: 
      context: ./redis-sentinel-cluster
    deploy:
      replicas: 3
    depends_on:
      - redis-master