version: '3.8'

services:
  web-api:
    build:
      args:
        PUBLISH_MODE: Debug
    env_file:
      - ../Store.WebAPI/variables.env # need to move this to vault
    environment: 
      ASPNETCORE_ENVIRONMENT: Test
      ASPNETCORE_URLS: https://+:443
      StoreApp_Kestrel__Certificates__Default__Path: /https/penic-solutions.com_self-signed.pfx

  database-update:
    env_file:
      - ../Store.WebAPI/variables.env

  postgres-server:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: Store
    env_file:
      - ./postgres-server/variables.env