version: '3.8'

services:
  web-api:
    build:
      context: ../
      dockerfile: ./Store.WebAPI/Dockerfile
      args:
        PUBLISH_MODE: Debug
    restart: always
    ports:
      - 5000:80
    env_file:
      - ../Store.WebAPI/variables.env
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres-server
      - redis-master

  database-update:
    build:
      context: ../
      dockerfile: ./Docker/database-update/Dockerfile
    volumes:
      - ../:/app
    env_file:
      - ../Store.WebAPI/variables.env
    depends_on:
        - postgres-server

  postgres-server:
    image: postgres:13
    ports: 
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: Store
    env_file:
      - ./postgres-server/variables.env

  redis-master:
    image: redis:6
    ports:
      - 6379:6379
  
  # Redis as a slave: https://redis.io/topics/config
  redis-slave-1:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6380:6379
      
  redis-slave-2:
    image: redis:6
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    ports:
      - 6381:6379
      
  # Redis Sentinel: https://redis.io/topics/sentinel
  redis-sentinel:
    build: 
      context: ./redis-sentinel-cluster
    deploy:
      replicas: 3
    depends_on:
      - redis-master

# GENERAL:
## Docker Context: https://docs.docker.com/engine/context/working-with-contexts/
## Volume is mapped only when the Dockerfile has been built successfully.