version: '3.8'

services:
  web-api:
    build:
      dockerfile: ./Store.WebAPI/test.Dockerfile
      args:
        PUBLISH_MODE: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      ASPNETCORE_URLS: https://+:443
      STOREAPP_KESTREL__CERTIFICATES__DEFAULT__PATH: /https/penic-solutions.com_self-signed.pfx

  database-update:
    environment:
      ASPNETCORE_ENVIRONMENT: Test

  postgres-server:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: Store
    env_file:
      - ./postgres-server_variables.env

  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
    env_file:
      - ./pgadmin_variables.env
    ports:
      - 5050:80
