version: '3.8'

services:
  web-api:
    build:
      args:
        PUBLISH_MODE: Debug
    env_file:
      - ../Store.WebAPI/variables.env
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      STOREAPP_KESTREL__CERTIFICATES__DEFAULT__PATH: /https/penic-solutions.com_self-signed.pfx

  database-update:
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - ./postgres-server_variables.env

  postgres-server:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: Store
    env_file:
      - ./pgadmin_variables.env